/**
 * Keap REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.70.0.736468-hf-202411121210
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RestProduct } from '../models/RestProduct';
import { HttpFile } from '../http/http';

export class ListProductsResponse {
    'nextPageToken'?: string;
    'products'?: Array<RestProduct>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string",
            "format": ""
        },
        {
            "name": "products",
            "baseName": "products",
            "type": "Array<RestProduct>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListProductsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
