/**
 * Keap REST API
 * Keap REST Core Service
 *
 * OpenAPI spec version: 2.70.0.778988
 * Contact: api@keap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductInterestBundle } from '../models/ProductInterestBundle';
import { HttpFile } from '../http/http';

export class ListProductInterestBundleResponse {
    'nextPageToken'?: string;
    'productInterestBundles'?: Array<ProductInterestBundle>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string",
            "format": ""
        },
        {
            "name": "productInterestBundles",
            "baseName": "product_interest_bundles",
            "type": "Array<ProductInterestBundle>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListProductInterestBundleResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
