/**
 * Keap REST API
 * Keap REST Core Service
 *
 * OpenAPI spec version: 2.70.0.778988
 * Contact: api@keap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ProductInventory {
    /**
    * The email address for notifications about inventory
    */
    'emailForInventoryNotifications'?: string;
    /**
    * The current inventory count for this product
    */
    'inventoryCount'?: number;
    /**
    * The inventory limit for this product
    */
    'inventoryLimit'?: number;
    /**
    * The flag to enable out of stock inventory
    */
    'outOfStockEnabled'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "emailForInventoryNotifications",
            "baseName": "email_for_inventory_notifications",
            "type": "string",
            "format": ""
        },
        {
            "name": "inventoryCount",
            "baseName": "inventory_count",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "inventoryLimit",
            "baseName": "inventory_limit",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "outOfStockEnabled",
            "baseName": "out_of_stock_enabled",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductInventory.attributeTypeMap;
    }

    public constructor() {
    }
}
