name: Publish Node Package to npmjs
on:
  release:
    types: [published]
  # Test
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      # Debugging step: List all files and folders recursively
      - name: Get path (debug)
        run: pwd
      - name: List all files after checkout (debug)
        run: ls -lR #a

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      # Javascript
      - name: Install Javascript dependencies
        working-directory: sdks/v2/javascript
        run: npm install

      - name: Publish Core Javascript package to npmjs
        run: npm publish --provenance --access public --dry-run
        working-directory: sdks/v2/javascript
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Typescript
      - name: Install Typescript dependencies
        working-directory: sdks/v2/typescript
        run: npm install

      - name: Publish Core Typescript package to npmjs
        run: npm publish --provenance --access public --dry-run
        working-directory: sdks/v2/typescript
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
