name: Publish Python Package to PyPI

on:
  release:
    types: [published]
  # Test
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build Core package
      working-directory: sdks/v2/python
      run: python setup.py sdist bdist_wheel

    - name: Publish Core package to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      working-directory: sdks/v2/python
      run: twine upload --repository-url https://test.pypi.org/legacy/ dist/* --verbose
